apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    layer: frontend
  name: frontend
  namespace: frontend-test
spec:
  replicas: 1
  selector:
    matchLabels:
      layer: frontend
  template:
    metadata:
      labels:
        layer: frontend
    spec:
      containers:
      - image: nginx:stable-bookworm
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
