apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_NAME
        
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_PASSWORD

        volumeMounts:
        - name: my-secret
          mountPath: "/usr/share/nginx/html"
          readOnly: false
      volumes:
      - name: my-secret
        secret:
          secretName: my-secret
