version: '3'
services:
  db:
    image: mysql:latest
    volumes:
     - mysqldb:/var/lib/mysql
    restart: always 
    environment:
       MYSQL_ROOT_PASSWORD: root123
       MYSQL_PASSWORD: root123
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
    networks:
       - pan_net
  wordpress:
    image: wordpress
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: always
    environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: root123
       WORDPRESS_DB_USER: wordpress
    networks:
       - pan_net
volumes:
  mysqldb:
networks:
  pan_net: