apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-all-allow
  namespace: frontend-test
spec:
  podSelector: {}
  ingress:
  egress:
  policyTypes:
  - Ingress
  - Egress
